Create mapper for same object reference and same array objects
mzweigert/M-MSON pull request #5
Opened 2017-04-23 12:23 UTC by mzweigert

2017-04-23 12:30 UTC, m-ciesielski commented on src/main/java/mmson/Main.java
> +        System.out.println(converter.toJson(p));
Zamiast do maina możnaby to wrzucić do testów i tam wywoływać `converter.ToJson`, tak jak to teraz jest robione.

2017-04-25 19:49 UTC, m-ciesielski requested changes

2017-04-25 19:49 UTC, m-ciesielski commented on src/main/java/mmson/MMSonConverter.java
> +                cache.put(c, wrapper);
Dlaczego do cache'a wrapper wrzucany jest dwa razy?

2017-04-25 19:49 UTC, m-ciesielski commented on src/main/java/mmson/MMSonConverter.java
> +import org.apache.commons.lang3.NotImplementedException;
Nieużywany import.

2017-04-25 19:49 UTC, m-ciesielski commented on src/main/java/mmson/FieldToJsonMapper.java
> +                    + " } else { sb.append(\"null\"); } ;";
Brakuje doklejania znaku końca listy `]`.

2017-04-25 20:48 UTC, mzweigert commented on src/main/java/mmson/MMSonConverter.java
> +                cache.put(c, wrapper);
zmienione na replace

2017-04-25 20:53 UTC, m-ciesielski requested changes

2017-04-25 20:53 UTC, m-ciesielski commented on src/main/java/mmson/MMSonConverter.java
> +                cache.replace(c, wrapper);
Ale do czego potrzebny jest ten replace? Do cache'a wrzucamy wrappera i potem ustawiamy mu odpowiednie pole, nie trzeba podmieniać obiektu w cache'u na ten sam obiekt.

2017-04-26 14:53 UTC, m-ciesielski approved these changes

2017-04-26 14:54 UTC, merged